OHRM5X-1964: Setup Initial Oauth Flow
orangehrm/orangehrm-os-mobile pull request #48
Opened 2023-03-17 09:34 UTC by ManulMax

2023-03-24 07:18 UTC, RajithaKumara requested changes

2023-03-24 07:18 UTC, RajithaKumara commented on src/layouts/DrawerContent.tsx
> +        name={myInfo?.employee.firstName + ' ' + myInfo?.employee.lastName}
will create helper method

2023-03-24 07:18 UTC, RajithaKumara commented on src/screens/login/Login.tsx
will remove this file, and route related to this and types

2023-03-24 07:18 UTC, RajithaKumara commented on src/services/endpoints.ts
> +// export const API_ENDPOINT_HELP_CONFIG = '/api/v1/help/config';
will remove API call related

2023-03-24 07:18 UTC, RajithaKumara commented on src/store/auth/reducer.ts
> +        isAuthenticated: true,
need to check and will separate to new action (under store/storage/reducer ; username)

2023-03-27 07:17 UTC, RajithaKumara approved these changes

2023-03-27 07:17 UTC, RajithaKumara commented on src/store/saga-effects/api.ts
> +export function* apiDeleteCall(endpoint: string) {
missing delete body

2023-03-27 07:17 UTC, RajithaKumara commented on src/store/help/sagas.ts
remove this

2023-03-27 07:17 UTC, RajithaKumara commented on src/layouts/DrawerContent.tsx
>    const onPressHelp = () => {
```jsx
  const onPressHelp = () => {
    Linking.canOpenURL(HELP_REDIRECT_URL).then((supported) => {
      if (supported) {
          Linking.openURL(HELP_REDIRECT_URL);
      }
    });
  };
```

2023-03-27 07:17 UTC, RajithaKumara commented on src/layouts/DrawerContent.tsx
>          imageSource={imageSource}
TODO

2023-03-27 07:17 UTC, RajithaKumara commented on src/store/auth/sagas.ts
> +      // TODO
TODO

2023-03-27 07:17 UTC, RajithaKumara commented on src/store/auth/sagas.ts
> +        },
TODO

2023-03-27 07:17 UTC, RajithaKumara commented on src/store/auth/sagas.ts
> +        if (!enabledModules.modules.mobile) {
TODO

2023-03-27 07:17 UTC, RajithaKumara commented on src/store/auth/sagas.ts
> +        iosPrefersEphemeralSession: true,
TODO:: invalid in types

2023-03-27 07:17 UTC, RajithaKumara commented on src/store/auth/sagas.ts
> +            },
TODO

2023-03-27 07:17 UTC, RajithaKumara commented on src/store/auth/sagas.ts
> +function* fetchApiDefinition() {
```suggestion
function* fetchRestApiVersion() {
```

2023-03-27 07:17 UTC, RajithaKumara commented on src/store/auth/sagas.ts
> +    if (
TODO

2023-03-27 07:17 UTC, RajithaKumara commented on src/store/auth/types.ts
>    supervisor: null | Supervisor[];
TODO:: refactor remove unnecessary

2023-03-27 07:17 UTC, RajithaKumara commented on src/store/auth/types.ts
>    isSupervisor: boolean;
TODO:: find alternative way to handle this

2023-03-27 08:02 UTC, merged

2023-03-27 11:15 UTC, ManulMax commented on src/screens/login/Login.tsx
removed