OHRM5X-1974/1975 : Implement punchIn/out screens api
orangehrm/orangehrm-os-mobile pull request #51
Opened 2023-04-03 11:48 UTC by ShehanOHRM

2023-04-04 02:46 UTC, RajithaKumara requested changes

2023-04-04 02:46 UTC, RajithaKumara commented on src/screens/time/Punch.tsx
> +        this.props.myInfo?.user.isSupervisor === true
this we have to remove

2023-04-04 02:46 UTC, RajithaKumara commented on src/screens/time/Punch.tsx
> +
```jsx
const prevPunchCurrentDateTime = prevProps.punchCurrentDate + ':' + prevProps.punchCurrentTime;
const punchCurrentDateTime = this.props.punchCurrentDate + ':' + this.props.punchCurrentTime;

if (prevPunchCurrentDateTime !== punchCurrentDateTime &&
      this.props.punchStatus?.state.name === PUNCHED_IN
    )
```

2023-04-04 02:46 UTC, RajithaKumara commented on src/screens/time/Punch.tsx
> +    this.props.changePunchCurrentDateTime(date, time);
*

2023-04-04 02:46 UTC, RajithaKumara commented on src/screens/time/Punch.tsx
> -        datetime: getDateSaveFormatFromDateObject(punchCurrentDateTime),
I think we can remove `getDateSaveFormatFromDateObject` method if not using anymore

2023-04-04 02:46 UTC, RajithaKumara commented on src/screens/time/Punch.tsx
> +      } else if (this.props.punchStatus?.state.name === INITIAL) {
Not sure this state still work with 5.x APIs

2023-04-04 02:46 UTC, RajithaKumara commented on src/screens/time/Punch.tsx
> +                            {punchStatus?.state.name === PUNCHED_IN
*

2023-04-04 02:46 UTC, RajithaKumara commented on src/screens/time/Punch.tsx
> +      myInfo?.user.isSupervisor === true
neet to check this

2023-04-04 02:46 UTC, RajithaKumara commented on src/screens/time/PunchRequestSuccess.tsx
> +import {PunchRequestSuccessParam} from './navigators';
```suggestion
import {PunchRequestSuccessParam} from 'screens/time/navigators/index';
```
:thinking:

2023-04-04 02:46 UTC, RajithaKumara commented on src/services/endpoints.ts
> +export const API_ENDPOINT_ATTENDANCE_CONFIG = '/api/v2/attendance/configs';
this may be a admin users endpoint

2023-04-04 02:46 UTC, RajithaKumara commented on src/store/time/punch/reducer.ts
> -          punchCurrentDateTime: getUTCDateObjectFromSaveFormat(
remove `getUTCDateObjectFromSaveFormat` method if not using anymore

2023-04-07 10:20 UTC, ShehanOHRM commented on src/screens/time/Punch.tsx
> +      myInfo?.user.isSupervisor === true
remove this part

2023-04-10 11:39 UTC, RajithaKumara commented
closing as moved to #53

2023-04-10 11:39 UTC, closed without merging