OHRM5X-2064:implement graph api
orangehrm/orangehrm-os-mobile pull request #57
Opened 2023-04-18 05:10 UTC by ShehanOHRM

2023-04-18 11:30 UTC, RajithaKumara requested changes

2023-04-18 11:30 UTC, RajithaKumara commented on src/screens/time/AttendancePickEmployee.tsx
> +  fetchSubordinates: DebouncedFunc<(text: string) => {}>;
```suggestion
  fetchSubordinates: DebouncedFunc<(text: string) => {}>;

```
add new line

2023-04-18 11:30 UTC, RajithaKumara commented on src/lib/helpers/attendance.ts
> +  graphData: GraphRecordsDetailsArray[],
```suggestion
  graphData: GraphRecordsDetails[],
```

2023-04-18 11:30 UTC, RajithaKumara commented on src/lib/helpers/attendance.ts
> +    const graphDataArray: GraphRecordsDetailsObject[] = [];
```suggestion
    const graphDataArray: GraphRecordsDetails[] = [];
```

2023-04-18 11:30 UTC, RajithaKumara commented on src/screens/time/AttendancePickEmployee.tsx
> +    this.fetchSubordinates = debounce((text: string) => {
:ok_hand:

2023-04-18 11:30 UTC, RajithaKumara commented on src/screens/time/AttendanceSummary.tsx
> +import {selectMyInfo} from '../../store/auth/selectors';
```suggestion
import {selectMyInfo} from 'store/auth/selectors';
```

2023-04-18 11:30 UTC, RajithaKumara commented on src/screens/time/AttendanceSummary.tsx
> +        ? getFirstAndLastNames(this.props.route.params?.employeeAttendance)
```suggestion
        ? getFirstAndLastNames(this.props.route.params.employeeAttendance)
```

2023-04-18 11:30 UTC, RajithaKumara commented on src/services/endpoints.ts
> +export const API_ENDPOINT_GRAPH_LEAVE_RECORDS =
```suggestion
export const API_ENDPOINT_EMPLOYEE_LEAVE =
```
:thinking:

2023-04-18 11:30 UTC, RajithaKumara commented on src/store/time/attendance/sagas.ts
> +          statuses: ['1', '2', '3'],
```suggestion
          statuses: ['1', '2', '3'], // pending approval, scheduled, taken
```
will add comment like this

2023-04-18 11:30 UTC, RajithaKumara commented on src/store/time/attendance/sagas.ts
> +            }),
:thinking:

2023-04-18 11:30 UTC, RajithaKumara commented on src/store/time/attendance/sagas.ts
> +    const workWeekResponse: ApiResponse<WorkSummaryGraphObject[]> =
I'm not clear on this

2023-04-18 11:30 UTC, RajithaKumara commented on src/store/time/attendance/types.ts
> +
```suggestion
```

2023-04-20 08:07 UTC, RajithaKumara requested changes

2023-04-20 08:07 UTC, RajithaKumara commented on ios/Carthage/Checkouts/AppAuth-iOS/.codecov.yml
> +ignore:
any idea about this?

2023-04-20 08:07 UTC, RajithaKumara commented on src/lib/helpers/attendance.ts
> +  return LEAVE_TYPE_COLORS[parseInt(String(id), 10) % LEAVE_TYPE_COLORS.length];
```suggestion
  return LEAVE_TYPE_COLORS[id % LEAVE_TYPE_COLORS.length];
```
:thinking:

2023-04-20 08:07 UTC, RajithaKumara commented on src/lib/helpers/attendance.ts
> +  if (leaves) {
```suggestion
```
I don't think we need this condition

2023-04-20 08:07 UTC, RajithaKumara commented on src/lib/helpers/attendance.ts
> +    if (workData) {
```suggestion
```
:thinking:

2023-04-20 08:07 UTC, RajithaKumara commented on src/screens/time/AttendanceDetails.tsx
> +import {selectMyInfo} from '../../store/auth/selectors';
```suggestion
import {selectMyInfo} from 'store/auth/selectors';
```

2023-04-20 08:07 UTC, RajithaKumara commented on src/screens/time/AttendancePickEmployee.tsx
>    };
*

2023-04-20 08:07 UTC, RajithaKumara commented on src/store/time/attendance/sagas.ts
> +    const workWeekResponse: ApiResponse<
```suggestion
    const workSummaryResponse: ApiResponse<
```

2023-04-20 08:07 UTC, RajithaKumara commented on src/store/time/attendance/types.ts
> +export const ESS = 'ESS';
do we still need this

2023-04-20 08:07 UTC, RajithaKumara commented on src/store/time/attendance/types.ts
> +export interface currentWeekObject {
```suggestion
export interface CurrentWeekObject {
```
refactor rename

2023-04-20 08:07 UTC, RajithaKumara commented on src/store/time/attendance/types.ts
> +}
do we need this
```suggestion
```

2023-04-20 08:07 UTC, RajithaKumara commented on src/store/time/attendance/types.ts
> +export interface GraphRecordsDetailsObject {
```suggestion
export interface GraphRecordsDetails {
```

2023-04-20 10:35 UTC, ShehanOHRM commented on ios/Carthage/Checkouts/AppAuth-iOS/.codecov.yml
> +ignore:
This file using a IOS auth login flow

2023-04-20 10:47 UTC, merged